<?php

/**
 * Story
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    continuethisstory
 * @subpackage model
 * @author     Saad Tazi
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Story extends BaseStory
{
    /**
     *
     * @param int $sfGuardUserId
     * @return boolean
     */
    public function isAdmin($sfGuardUserId) {
	return $sfGuardUserId == $this->creator_id;
    }
        
}