parameters:
#    saad_tazi_continue_this_story.example.class: SaadTazi\ContinueThisStoryBundle\Example

services:
#    saad_tazi_continue_this_story.example:
#        class: %saad_tazi_continue_this_story.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
